# Generated by Django 4.2.16 on 2024-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0002_person_hat_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=60)),
            ],
        ),
    ]
